### ISSUE TITLE
Add convert support for ordered factors

### ISSUE THREAD

**Issue by StaffanBetner** [davidsjoberg/hablar#1]
Since fct uses as.factor, which doesn't take any other arguments other than a vector, it isn't possible to use convert to make a variable an ordered factor. One way to solve this might be to change from as.factor to factor, or add a function "ord" which would be a wrapper for as.ordered, or some combination of both since as.* cannot take arguments levels and labels.

**Comment by StaffanBetner** [comment]
PR #2

**Comment by davidsjoberg** [comment]
Merged your pull request. Thanks for spotting the problem!
