### ISSUE TITLE
FYI: `na_if` has a name conflict with **dplyr**

### ISSUE THREAD

**Issue by phargarten2** [davidsjoberg/hablar#10]
As **hablar** was designed with **dplyr** in mind, I thought you should be aware of this name conflict, that is, if you are not aware of this already.  Depending on the order of loading the **hablar** and **dplyr** packages, hablar's `na_if()` now can mask dplyr `na_if()` ...which again may cause issues for unaware R users. This is not as bad as I can always use `::` with limited readability if I want to use this function.

```{r}
library(dplyr)
library(hablar)
Attaching package: ‘hablar’

The following object is masked from ‘package:dplyr’:

    na_if

The following object is masked from ‘package:tibble’:

    num
```

I can use hablar's `na_if()` explicitly without sacrificing readability. Trivialy, if this is a part of a larger sequence, 

```{r}
c(1, NA, 2) %>%
   hablar::na_if(v == 1)   
```
Using `dplyr::na_if(v == 1)` yields the same answer in this case.

**Comment by davidsjoberg** [comment]
Thanks for bringing it up. I dont want to ruin backwards compability at this point. So I close this for now.
