### ISSUE TITLE
hablar::retype strips the time from date-times

### ISSUE THREAD

**Issue by entropitor** [davidsjoberg/hablar#12]
```R
> Sys.time()
[1] "2022-04-29 09:50:12 CEST"
> class(Sys.time())
[1] "POSIXct" "POSIXt"

> hablar::retype(Sys.time())
[1] "2022-04-29"
> class(hablar::retype(Sys.time()))
[1] "Date"
```

It feels like the above is a bug. I get that datetime should be converted if there is no useful information in the time part but in general, it seems to strip the time off as shown above.

**Comment by nathaniel-mahieu** [comment]
Just ran into this as well.  This is a bug when starting with string datetimes as well.

> hablar::retype("2022-05-12 21:04:05.000000000 +0000")
[1] "2022-05-12"
