### ISSUE TITLE
I like your R packgaes hablar very much！hope it can more better

### ISSUE THREAD

**Issue by wangjiaxuan666** [davidsjoberg/hablar#4]
A small issue：
If you don’t change it, it won’t matter. But the Error messages should be changed,

`hablar` can't use like this :
```
cars %>% convert(chr(cars$dist))
# Error in inds_combine(.vars, ind_list) : Position must be between 0 and n
```
but it can
```
cars %>% convert(chr(dist))
```
if it can use in this way like `cars$dist`, it will be more better.

sorry ,I didn't use the google translate, forgive my poor English!

I predict your R package will be hot！
目测会火，前排留言

**Comment by davidsjoberg** [comment]
Thanks @wangjiaxuan666  for your comment! I will try to  review all error messages for the next version of hablar. I'll leave this issue open so i do not forget.

**Comment by davidsjoberg** [comment]
Probabaly a bit out of scope for the use case.
