### ISSUE TITLE
Possible to preserve the specific data.frame type?

### ISSUE THREAD

**Issue by RoyceWHowland** [davidsjoberg/hablar#5]
Hi there! I've just started using hablar to help with data cleaning on a current project. So far it is proving to add convenience when dealing with messy data, as well as NaN, Inf and so on.

One enhancement request I have is if functions such as rationalize() and the find_() variants can preserve the specific type of data.frame. I'm doing a bunch of time series work for which it is helpful to have all my data represented as fable tsibbles instead of standard tibbles. I'd love to be able to apply hablar features to the tsibbles without losing their structure via the associated metadata such as index and key variables.

Thanks for the work on this package!

**Comment by davidsjoberg** [comment]
Better late than never. I solved the issue. Sending to CRAN soon.
