### ISSUE TITLE
Large numbers return NA in could_num_be_int.  NA throws error in hablar::retype

### ISSUE THREAD

**Issue by nathaniel-mahieu** [davidsjoberg/hablar#7]
20211031212817 %>% could_num_be_int
[1] NA

20211031212817 %>% retype

Error in if (could_num_be_int(.x) == TRUE) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In ifelse(all(.x[!is.na(.x)] == as.integer(.x[!is.na(.x)])), TRUE,  :
  NAs introduced by coercion to integer range

**Comment by magnusnes** [comment]
The error is probably caused by your integer being larger than`.Machine$integer.max`, a case not handled by the code. 

A solution could be to add `| any(.x > .Machine$integer.max)` [here](https://github.com/davidsjoberg/hablar/blob/master/R/hablar.R#L86).
